-- =============================================================================
-- TOV640 Analyzer - SQLite Database Schema
-- =============================================================================
-- Version: 1.0
-- Date: 2026-01-30
-- Purpose: Stateful Transformation + Database Record Module
-- =============================================================================

-- Enable Foreign Keys
PRAGMA foreign_keys = ON;

-- =============================================================================
-- SECTION 1: STATEFUL TRANSFORMATION TABLES (Auto-Persistence)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: analysis_sessions
-- Purpose: Store analysis session metadata (auto-created on each analysis run)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS analysis_sessions (
    id TEXT PRIMARY KEY,                      -- UUID (generated by backend)
    
    -- Analysis Metadata
    line TEXT NOT NULL,                       -- EAL / TML / etc.
    section TEXT NOT NULL,                    -- Mainline / RAC / LOW / LMC
    track TEXT NOT NULL,                      -- UP / DOWN
    date_str TEXT NOT NULL,                   -- Analysis date (YYYYMMDD)
    
    -- File Reference (raw data NOT stored, only path reference)
    raw_data_file_path TEXT,                  -- Full path to .datac file
    raw_data_file_name TEXT,                  -- Original filename
    raw_data_file_size INTEGER,               -- File size in bytes
    
    -- Optional Metadata
    task_no TEXT,                             -- User-defined task number
    station_start TEXT,                       -- Start station name
    station_end TEXT,                         -- End station name
    
    -- Analysis Statistics (denormalized for quick access)
    total_exceptions INTEGER DEFAULT 0,
    l1_count INTEGER DEFAULT 0,               -- Critical
    l2_count INTEGER DEFAULT 0,               -- Warning
    l3_count INTEGER DEFAULT 0,               -- Info
    
    -- Status Management
    status TEXT DEFAULT 'completed' CHECK(status IN ('pending', 'completed', 'failed', 'archived')),
    
    -- Timestamps
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    analyzed_at DATETIME,
    last_modified DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    -- Indexable Constraints
    UNIQUE(line, track, date_str, section, raw_data_file_name)
);

-- -----------------------------------------------------------------------------
-- Table: exceptions
-- Purpose: Store individual exception records (auto-saved during analysis)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exceptions (
    id TEXT PRIMARY KEY,                      -- UUID (from ExceptionRecord.id)
    session_id TEXT NOT NULL,                 -- FK to analysis_sessions
    
    -- Exception Details (mirrors ExceptionRecord interface)
    exception_type TEXT NOT NULL,             -- 'Low Height', 'High Height', 'Wire Wear', 'Stagger Left', 'Stagger Right'
    level TEXT NOT NULL CHECK(level IN ('L1', 'L2', 'L3')),
    from_m REAL NOT NULL,                     -- Start chainage (meters)
    to_m REAL NOT NULL,                       -- End chainage (meters)
    length REAL,                              -- Exception length
    max_value REAL,                           -- Peak value
    max_location REAL,                        -- Location of peak value
    
    -- Track Classification
    track_type TEXT,                          -- Track type classification
    overlap TEXT,                             -- Overlap zone information
    tension_length TEXT,                      -- Tension length value
    landmark TEXT,                            -- Nearest landmark
    class TEXT,                               -- Classification (both, LMC, etc.)
    threshold_value REAL,                     -- Applied threshold value
    section TEXT,                             -- Section classification
    
    -- Workflow Status (for Stateful management)
    current_status TEXT DEFAULT 'pending' CHECK(current_status IN ('pending', 'in_progress', 'resolved', 'deferred', 'false_positive')),
    assigned_to TEXT,                         -- Person responsible
    notes TEXT,                               -- General notes
    priority INTEGER DEFAULT 0,               -- 0=Normal, 1=High, 2=Critical
    
    -- Resolution Tracking
    resolved_at DATETIME,
    resolved_by TEXT,
    resolution_notes TEXT,
    
    -- Timestamps
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_modified DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign Key
    FOREIGN KEY (session_id) REFERENCES analysis_sessions(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: exception_history
-- Purpose: Track status changes for audit trail
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS exception_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exception_id TEXT NOT NULL,               -- FK to exceptions
    
    -- Change Record
    old_status TEXT,
    new_status TEXT NOT NULL,
    changed_by TEXT,                          -- Who made the change
    change_reason TEXT,                       -- Why the change was made
    
    -- Metadata
    changed_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign Key
    FOREIGN KEY (exception_id) REFERENCES exceptions(id) ON DELETE CASCADE
);

-- -----------------------------------------------------------------------------
-- Table: reports
-- Purpose: Track report generation history
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reports (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    session_id TEXT NOT NULL,                 -- FK to analysis_sessions
    
    -- Report Details
    report_type TEXT NOT NULL CHECK(report_type IN ('excel', 'pdf', 'csv', 'json')),
    file_name TEXT NOT NULL,
    file_path TEXT,
    file_size INTEGER,
    
    -- Report Metadata
    generated_by TEXT,
    include_charts INTEGER DEFAULT 1,         -- Boolean: include chart data
    include_metadata INTEGER DEFAULT 1,       -- Boolean: include __metadata__ sheet
    
    -- Version Control (for Excel sync)
    db_version_at_export INTEGER,             -- Database version when exported
    schema_version TEXT,                      -- Schema version
    
    -- Timestamps
    generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    -- Foreign Key
    FOREIGN KEY (session_id) REFERENCES analysis_sessions(id) ON DELETE SET NULL
);

-- -----------------------------------------------------------------------------
-- Table: system_metadata
-- Purpose: Store system configuration and version control
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_metadata (
    key TEXT PRIMARY KEY,
    value TEXT,
    description TEXT,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Initialize system metadata with default values
INSERT OR IGNORE INTO system_metadata (key, value, description) VALUES
    ('schema_version', '1.7', 'Database schema version'),
    ('db_version', '1', 'Auto-incrementing database version for sync'),
    ('wire_wear_data_version', '0', 'Wire wear data version for sync'),
    ('created_at', datetime('now'), 'Database creation timestamp'),
    ('last_migration', '1.7', 'Last applied migration version'),
    ('application_version', '2.0.0', 'TOV640 Analyzer application version');

-- =============================================================================
-- SECTION 2: DATABASE RECORD MODULE TABLES (Manual Save)
-- =============================================================================

-- NOTE: Sub-module 1 (saved_exception_records) has been DEPRECATED and REMOVED
-- as of 2026-01-31. All exception record storage is now handled via Sub-module 2.

-- -----------------------------------------------------------------------------
-- Table: saved_repeated_exceptions
-- Purpose: Sub-module 2 - Repeated exceptions from HistoryCompareView with Follow-up Action tracking
-- Note: Does NOT store chartData, and MOCK_DATA (id starts with 'mock-') is filtered out
-- 
-- ENHANCEMENT (2026-01-31): Added 9 new workflow columns to align with ComparisonDataGrid:
-- - reoccurrence_id: Links to historical database record (Check 1 year Record feature)
-- - Site Verification group: verify_deadline, verify_date, verify_result, verified_by
-- - Final Adjustment group: adjust_deadline, adjust_date, adjust_result, adjusted_by
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS saved_repeated_exceptions (
    -- Primary Key (auto-increment because same exception can appear in multiple comparison runs)
    record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    exception_id TEXT NOT NULL,               -- Original ExceptionRecord.id (NOT mock-*)
    
    -- Exception Details (inherited from ExceptionRecord)
    exception_type TEXT NOT NULL,
    level TEXT NOT NULL CHECK(level IN ('L1', 'L2', 'L3')),
    from_m REAL NOT NULL,
    to_m REAL NOT NULL,
    length REAL,
    max_value REAL,
    max_location REAL,
    track_type TEXT,
    overlap TEXT,
    tension_length TEXT,
    landmark TEXT,
    class TEXT,
    threshold_value REAL,
    section TEXT,
    
    -- Repeated Exception Specific Fields (from ComparisonDataGrid)
    previous_1 TEXT,                          -- Exception ID from previous analysis (1)
    previous_2 TEXT,                          -- Exception ID from previous analysis (2)
    repeat_count INTEGER DEFAULT 2,           -- Number of times this exception appeared
    
    -- Reoccurrence Tracking (NEW: 2026-01-31)
    reoccurrence_id TEXT,                     -- Links to historical record ID (for Check 1 year Record feature)
    
    -- Initial Check Workflow Fields (EDITABLE)
    action TEXT,                              -- 'Pending', 'Keep monitoring', 'Calculation', 'Verify on site', 'No action required', etc.
    check_date TEXT,                          -- Scheduled check date (YYYY-MM-DD)
    checked_by TEXT,                          -- Person who checked
    check_result TEXT,                         -- Calculation result ('Pass', 'Fail', 'N/A')
    remarks TEXT,                             -- Additional remarks
    
    -- Site Verification Workflow Fields (NEW: 2026-01-31)
    verify_deadline TEXT,                     -- Verification deadline (YYYY-MM-DD)
    verify_date TEXT,                         -- Actual verification date (YYYY-MM-DD)
    verify_result TEXT,                       -- Verification result ('Pass', 'Fail', 'N/A')
    verified_by TEXT,                         -- Person who verified
    
    -- Final Adjustment Workflow Fields (NEW: 2026-01-31)
    adjust_deadline TEXT,                     -- Adjustment deadline (YYYY-MM-DD)
    adjust_date TEXT,                         -- Actual adjustment date (YYYY-MM-DD)
    adjust_result TEXT,                       -- Adjustment result ('Pass', 'Fail', 'N/A')
    adjusted_by TEXT,                         -- Person who adjusted
    
    -- Task Run Data (identifies the comparison context)
    line TEXT NOT NULL,
    track TEXT NOT NULL,
    date_str TEXT NOT NULL,                   -- Latest analysis date (YYYYMMDD)
    task_run_date TEXT,                       -- Task run date (YYYY/MM/DD format for display, stored as ISO)
    
    -- Optional Metadata
    task_no TEXT,
    station_start TEXT,
    station_end TEXT,
    
    -- Comparison Source Reference
    latest_file_name TEXT,                    -- Name of latest Excel file in comparison
    comparison_files TEXT,                    -- JSON array of file names used in comparison
    
    -- System Fields
    saved_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    saved_by TEXT,
    last_updated DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    -- Prevent duplicate saves of the same repeated exception
    UNIQUE(exception_id, line, track, date_str)
);

-- =============================================================================
-- SECTION 3: INDEXES (Performance Optimization)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- analysis_sessions indexes
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_sessions_line_track ON analysis_sessions(line, track);
CREATE INDEX IF NOT EXISTS idx_sessions_date ON analysis_sessions(date_str);
CREATE INDEX IF NOT EXISTS idx_sessions_status ON analysis_sessions(status);
CREATE INDEX IF NOT EXISTS idx_sessions_created ON analysis_sessions(created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_metadata ON analysis_sessions(line, track, date_str);

-- -----------------------------------------------------------------------------
-- Table: wire_wear_records
-- Purpose: Wear Calculator internal database for cycle-level tension length wear
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wire_wear_records (
    record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    line_group TEXT NOT NULL CHECK(line_group IN ('EAL', 'TML')),
    line_class TEXT NOT NULL CHECK(line_class IN ('EAL', 'LMC', 'TML')),
    track TEXT NOT NULL,
    section TEXT NOT NULL,
    cycle_date TEXT NOT NULL,
    tension_length TEXT NOT NULL,
    from_m REAL NOT NULL,
    to_m REAL NOT NULL,
    avg_wear_min REAL NOT NULL,
    sd REAL NOT NULL DEFAULT 0,
    wear_percentage REAL NOT NULL,
    source_file_names TEXT,
    saved_by TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(line_group, line_class, track, section, cycle_date, tension_length)
);

CREATE INDEX IF NOT EXISTS idx_wire_wear_line_group
    ON wire_wear_records(line_group);
CREATE INDEX IF NOT EXISTS idx_wire_wear_line_class
    ON wire_wear_records(line_class);
CREATE INDEX IF NOT EXISTS idx_wire_wear_records_cycle_date
    ON wire_wear_records(cycle_date);
CREATE INDEX IF NOT EXISTS idx_wire_wear_tension_length
    ON wire_wear_records(tension_length);
CREATE INDEX IF NOT EXISTS idx_wire_wear_group_tl_date
    ON wire_wear_records(line_group, tension_length, cycle_date);

-- -----------------------------------------------------------------------------
-- Tables: normalized complete-cycle wire wear storage
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS wire_wear_cycles (
    cycle_id INTEGER PRIMARY KEY AUTOINCREMENT,
    line_group TEXT NOT NULL CHECK(line_group IN ('EAL', 'TML')),
    line_class TEXT NOT NULL CHECK(line_class IN ('EAL', 'LMC', 'TML')),
    cycle_date TEXT NOT NULL,
    source_type TEXT NOT NULL CHECK(source_type IN ('analysis', 'manual', 'sync')),
    acquisition_date_from TEXT,
    acquisition_date_to TEXT,
    completeness_state TEXT NOT NULL CHECK(completeness_state IN ('complete', 'incomplete')),
    source_lineage TEXT NOT NULL DEFAULT '[]',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(line_group, line_class, cycle_date)
);

CREATE TABLE IF NOT EXISTS wire_wear_cycle_segments (
    segment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cycle_id INTEGER NOT NULL,
    segment_name TEXT NOT NULL,
    is_present INTEGER NOT NULL CHECK(is_present IN (0, 1)),
    coverage_percentage REAL NOT NULL,
    diagnostic_gaps TEXT NOT NULL DEFAULT '[]',
    source_file_names TEXT NOT NULL DEFAULT '[]',
    acquisition_date_from TEXT,
    acquisition_date_to TEXT,
    UNIQUE(cycle_id, segment_name),
    FOREIGN KEY (cycle_id) REFERENCES wire_wear_cycles(cycle_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wire_wear_cycle_records (
    record_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cycle_id INTEGER NOT NULL,
    line_group TEXT NOT NULL CHECK(line_group IN ('EAL', 'TML')),
    line_class TEXT NOT NULL CHECK(line_class IN ('EAL', 'LMC', 'TML')),
    cycle_date TEXT NOT NULL,
    tension_length TEXT NOT NULL,
    track TEXT NOT NULL CHECK(track IN ('UP', 'DN', 'Siding')),
    from_m REAL NOT NULL,
    to_m REAL NOT NULL,
    avg_wear_min REAL NOT NULL,
    wear_percentage REAL NOT NULL,
    measurement_sd REAL,
    physical_intervals TEXT NOT NULL DEFAULT '[]',
    source_lineage TEXT NOT NULL DEFAULT '[]',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(line_group, line_class, cycle_date, tension_length),
    FOREIGN KEY (cycle_id) REFERENCES wire_wear_cycles(cycle_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wire_wear_conflict_decisions (
    decision_id INTEGER PRIMARY KEY AUTOINCREMENT,
    cycle_id INTEGER NOT NULL,
    measurement_identity TEXT NOT NULL,
    source_values TEXT NOT NULL,
    selected_wear_min REAL NOT NULL,
    accepted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(cycle_id, measurement_identity),
    FOREIGN KEY (cycle_id) REFERENCES wire_wear_cycles(cycle_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wire_wear_deletion_tombstones (
    tombstone_id INTEGER PRIMARY KEY AUTOINCREMENT,
    line_group TEXT NOT NULL CHECK(line_group IN ('EAL', 'TML')),
    line_class TEXT NOT NULL CHECK(line_class IN ('EAL', 'LMC', 'TML')),
    cycle_date TEXT NOT NULL,
    tension_length TEXT NOT NULL,
    deleted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_package_id TEXT,
    UNIQUE(line_group, line_class, cycle_date, tension_length)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_wire_wear_cycle_identity
    ON wire_wear_cycle_records(line_group, line_class, cycle_date, tension_length);
CREATE INDEX IF NOT EXISTS idx_wire_wear_cycle_tl_history
    ON wire_wear_cycle_records(line_group, line_class, tension_length, cycle_date);
CREATE UNIQUE INDEX IF NOT EXISTS ux_wire_wear_parent_cycle
    ON wire_wear_cycles(line_group, line_class, cycle_date);

-- -----------------------------------------------------------------------------
-- exceptions indexes
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_exceptions_session ON exceptions(session_id);
CREATE INDEX IF NOT EXISTS idx_exceptions_level ON exceptions(level);
CREATE INDEX IF NOT EXISTS idx_exceptions_type ON exceptions(exception_type);
CREATE INDEX IF NOT EXISTS idx_exceptions_status ON exceptions(current_status);
CREATE INDEX IF NOT EXISTS idx_exceptions_location ON exceptions(from_m, to_m);
CREATE INDEX IF NOT EXISTS idx_exceptions_priority ON exceptions(priority, current_status);

-- -----------------------------------------------------------------------------
-- exception_history indexes
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_history_exception ON exception_history(exception_id);
CREATE INDEX IF NOT EXISTS idx_history_changed_at ON exception_history(changed_at);

-- -----------------------------------------------------------------------------
-- saved_repeated_exceptions indexes (Sub-module 2)
-- NOTE: Sub-module 1 (saved_exception_records) indexes REMOVED as of 2026-01-31
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_repeated_metadata ON saved_repeated_exceptions(line, track, date_str);
CREATE INDEX IF NOT EXISTS idx_repeated_level ON saved_repeated_exceptions(level);
CREATE INDEX IF NOT EXISTS idx_repeated_type ON saved_repeated_exceptions(exception_type);
CREATE INDEX IF NOT EXISTS idx_repeated_action ON saved_repeated_exceptions(action);
CREATE INDEX IF NOT EXISTS idx_repeated_location ON saved_repeated_exceptions(from_m, to_m);
CREATE INDEX IF NOT EXISTS idx_repeated_saved_at ON saved_repeated_exceptions(saved_at);
CREATE INDEX IF NOT EXISTS idx_repeated_check_date ON saved_repeated_exceptions(check_date);
-- NEW indexes for enhanced workflow fields (2026-01-31)
CREATE INDEX IF NOT EXISTS idx_repeated_reoccurrence ON saved_repeated_exceptions(reoccurrence_id);
CREATE INDEX IF NOT EXISTS idx_repeated_verify_deadline ON saved_repeated_exceptions(verify_deadline);
CREATE INDEX IF NOT EXISTS idx_repeated_adjust_deadline ON saved_repeated_exceptions(adjust_deadline);
-- Composite index for Check 1 year Record feature (location + date lookup)
CREATE INDEX IF NOT EXISTS idx_repeated_location_date ON saved_repeated_exceptions(from_m, to_m, date_str);
-- NEW index for Task Run Date filter (2026-02-01)
CREATE INDEX IF NOT EXISTS idx_repeated_task_run_date ON saved_repeated_exceptions(task_run_date);

-- =============================================================================
-- SECTION 4: VIEWS (Pre-defined Query Helpers)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- View: v_sessions_with_stats
-- Purpose: Sessions with exception statistics (denormalized for dashboard)
-- -----------------------------------------------------------------------------
CREATE VIEW IF NOT EXISTS v_sessions_with_stats AS
SELECT 
    s.id,
    s.line,
    s.section,
    s.track,
    s.date_str,
    s.status,
    s.created_at,
    s.analyzed_at,
    s.total_exceptions,
    s.l1_count,
    s.l2_count,
    s.l3_count,
    s.task_no,
    s.station_start,
    s.station_end,
    s.raw_data_file_name,
    -- Calculated fields
    COALESCE(
        (SELECT COUNT(*) FROM exceptions e 
         WHERE e.session_id = s.id AND e.current_status = 'pending'), 0
    ) AS pending_count,
    COALESCE(
        (SELECT COUNT(*) FROM exceptions e 
         WHERE e.session_id = s.id AND e.current_status = 'in_progress'), 0
    ) AS in_progress_count,
    COALESCE(
        (SELECT COUNT(*) FROM exceptions e 
         WHERE e.session_id = s.id AND e.current_status = 'resolved'), 0
    ) AS resolved_count
FROM analysis_sessions s
ORDER BY s.created_at DESC;

-- -----------------------------------------------------------------------------
-- View: v_pending_critical_exceptions
-- Purpose: All pending L1 (critical) exceptions across all sessions
-- -----------------------------------------------------------------------------
CREATE VIEW IF NOT EXISTS v_pending_critical_exceptions AS
SELECT 
    e.id,
    e.session_id,
    e.exception_type,
    e.level,
    e.from_m,
    e.to_m,
    e.max_value,
    e.current_status,
    e.priority,
    e.assigned_to,
    e.created_at,
    s.line,
    s.track,
    s.section,
    s.date_str
FROM exceptions e
JOIN analysis_sessions s ON e.session_id = s.id
WHERE e.level = 'L1' 
  AND e.current_status IN ('pending', 'in_progress')
ORDER BY 
    e.priority DESC,
    e.created_at ASC;

-- -----------------------------------------------------------------------------
-- View: v_repeated_exception_summary_by_date
-- Purpose: Aggregate repeated exception statistics by date and line
-- NOTE: Renamed from v_exception_summary_by_date (2026-01-31)
-- -----------------------------------------------------------------------------
CREATE VIEW IF NOT EXISTS v_repeated_exception_summary_by_date AS
SELECT 
    line,
    track,
    date_str,
    COUNT(*) AS total_count,
    SUM(CASE WHEN level = 'L1' THEN 1 ELSE 0 END) AS l1_count,
    SUM(CASE WHEN level = 'L2' THEN 1 ELSE 0 END) AS l2_count,
    SUM(CASE WHEN level = 'L3' THEN 1 ELSE 0 END) AS l3_count,
    MIN(saved_at) AS first_saved,
    MAX(saved_at) AS last_saved
FROM saved_repeated_exceptions
GROUP BY line, track, date_str
ORDER BY date_str DESC;

-- -----------------------------------------------------------------------------
-- View: v_pending_repeated_exceptions
-- Purpose: Repeated exceptions requiring follow-up action
-- -----------------------------------------------------------------------------
CREATE VIEW IF NOT EXISTS v_pending_repeated_exceptions AS
SELECT 
    record_id,
    exception_id,
    exception_type,
    level,
    from_m,
    to_m,
    max_value,
    line,
    track,
    date_str,
    action,
    repeat_count,
    check_date,
    checked_by,
    saved_at,
    last_updated
FROM saved_repeated_exceptions
WHERE action IN ('Pending', 'Keep monitoring', NULL, '')
   OR (action = 'Calculation' AND (check_result IS NULL OR check_result = ''))
ORDER BY 
    CASE level 
        WHEN 'L1' THEN 1 
        WHEN 'L2' THEN 2 
        WHEN 'L3' THEN 3 
    END,
    saved_at DESC;

-- =============================================================================
-- SECTION 5: TRIGGERS (Automated Maintenance)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Trigger: trg_sessions_update_timestamp
-- Purpose: Auto-update last_modified when analysis_sessions is updated
-- -----------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS trg_sessions_update_timestamp
AFTER UPDATE ON analysis_sessions
FOR EACH ROW
BEGIN
    UPDATE analysis_sessions 
    SET last_modified = CURRENT_TIMESTAMP 
    WHERE id = NEW.id;
END;

-- -----------------------------------------------------------------------------
-- Trigger: trg_exceptions_status_change
-- Purpose: Record status changes in exception_history table
-- -----------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS trg_exceptions_status_change
AFTER UPDATE OF current_status ON exceptions
FOR EACH ROW
WHEN OLD.current_status <> NEW.current_status
BEGIN
    INSERT INTO exception_history (exception_id, old_status, new_status, changed_at)
    VALUES (NEW.id, OLD.current_status, NEW.current_status, CURRENT_TIMESTAMP);
    
    -- Also update last_modified on the exception
    UPDATE exceptions 
    SET last_modified = CURRENT_TIMESTAMP 
    WHERE id = NEW.id;
END;

-- -----------------------------------------------------------------------------
-- Trigger: trg_increment_db_version
-- Purpose: Increment db_version in system_metadata when data changes
-- This supports the Excel sync version control mechanism
-- -----------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS trg_increment_db_version_sessions
AFTER INSERT ON analysis_sessions
BEGIN
    UPDATE system_metadata 
    SET value = CAST(value AS INTEGER) + 1,
        updated_at = CURRENT_TIMESTAMP
    WHERE key = 'db_version';
END;

CREATE TRIGGER IF NOT EXISTS trg_increment_db_version_exceptions
AFTER INSERT ON exceptions
BEGIN
    UPDATE system_metadata 
    SET value = CAST(value AS INTEGER) + 1,
        updated_at = CURRENT_TIMESTAMP
    WHERE key = 'db_version';
END;

-- NOTE: trg_increment_db_version_saved (for saved_exception_records) REMOVED as of 2026-01-31

CREATE TRIGGER IF NOT EXISTS trg_increment_db_version_repeated
AFTER INSERT ON saved_repeated_exceptions
BEGIN
    UPDATE system_metadata 
    SET value = CAST(value AS INTEGER) + 1,
        updated_at = CURRENT_TIMESTAMP
    WHERE key = 'db_version';
END;

CREATE TRIGGER IF NOT EXISTS trg_increment_db_version_wire_wear
AFTER INSERT ON wire_wear_records
BEGIN
    UPDATE system_metadata
    SET value = CAST(CAST(value AS INTEGER) + 1 AS TEXT),
        updated_at = CURRENT_TIMESTAMP
    WHERE key = 'db_version';
END;

-- -----------------------------------------------------------------------------
-- Trigger: trg_repeated_update_timestamp
-- Purpose: Auto-update last_updated when saved_repeated_exceptions is modified
-- -----------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS trg_repeated_update_timestamp
AFTER UPDATE ON saved_repeated_exceptions
FOR EACH ROW
BEGIN
    UPDATE saved_repeated_exceptions 
    SET last_updated = CURRENT_TIMESTAMP 
    WHERE record_id = NEW.record_id;
END;

CREATE TRIGGER IF NOT EXISTS trg_wire_wear_updated_at
AFTER UPDATE ON wire_wear_records
FOR EACH ROW
BEGIN
    UPDATE wire_wear_records
    SET updated_at = CURRENT_TIMESTAMP
    WHERE record_id = NEW.record_id;
END;

-- -----------------------------------------------------------------------------
-- Trigger: trg_update_session_stats
-- Purpose: Update denormalized exception counts on analysis_sessions
-- -----------------------------------------------------------------------------
CREATE TRIGGER IF NOT EXISTS trg_update_session_stats_insert
AFTER INSERT ON exceptions
FOR EACH ROW
BEGIN
    UPDATE analysis_sessions
    SET 
        total_exceptions = (SELECT COUNT(*) FROM exceptions WHERE session_id = NEW.session_id),
        l1_count = (SELECT COUNT(*) FROM exceptions WHERE session_id = NEW.session_id AND level = 'L1'),
        l2_count = (SELECT COUNT(*) FROM exceptions WHERE session_id = NEW.session_id AND level = 'L2'),
        l3_count = (SELECT COUNT(*) FROM exceptions WHERE session_id = NEW.session_id AND level = 'L3'),
        last_modified = CURRENT_TIMESTAMP
    WHERE id = NEW.session_id;
END;

CREATE TRIGGER IF NOT EXISTS trg_update_session_stats_delete
AFTER DELETE ON exceptions
FOR EACH ROW
BEGIN
    UPDATE analysis_sessions
    SET 
        total_exceptions = (SELECT COUNT(*) FROM exceptions WHERE session_id = OLD.session_id),
        l1_count = (SELECT COUNT(*) FROM exceptions WHERE session_id = OLD.session_id AND level = 'L1'),
        l2_count = (SELECT COUNT(*) FROM exceptions WHERE session_id = OLD.session_id AND level = 'L2'),
        l3_count = (SELECT COUNT(*) FROM exceptions WHERE session_id = OLD.session_id AND level = 'L3'),
        last_modified = CURRENT_TIMESTAMP
    WHERE id = OLD.session_id;
END;

-- =============================================================================
-- SECTION 6: MIGRATION SUPPORT
-- =============================================================================

-- Helper table for tracking schema migrations (future use)
CREATE TABLE IF NOT EXISTS schema_migrations (
    version TEXT PRIMARY KEY,
    applied_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    description TEXT
);

-- Record initial migration
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.0', 'Initial schema - Stateful Transformation + Database Record Module');

-- Migration 1.1: Remove Sub-module 1, Enhance Sub-module 2 (2026-01-31)
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.1', 'Remove saved_exception_records (Sub-module 1), Add 9 workflow columns to saved_repeated_exceptions: reoccurrence_id, verify_deadline, verify_date, verify_result, verified_by, adjust_deadline, adjust_date, adjust_result, adjusted_by');

-- Migration 1.2: Add task_run_date column (2026-02-01)
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.2', 'Add task_run_date column to saved_repeated_exceptions for Task Run Data group');

-- Migration 1.3: Add Wear Calculator wire wear records
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.3', 'Add wire_wear_records table for Wear Calculator saved cycle records');

-- Migration 1.4: Add aggregated Wear Calculator TL-cycle records
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.4', 'Add wire_wear_cycle_records table for aggregated Wear Calculator TL-cycle records');

-- Migration 1.5: Normalize complete-cycle wire wear storage
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.5', 'Normalize complete-cycle wire wear storage');
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.6', 'Preserve multi-interval wire wear metadata');
INSERT OR IGNORE INTO schema_migrations (version, description) VALUES
    ('1.7', 'Add required line_class to normalized wire wear identity');

-- =============================================================================
-- END OF SCHEMA
-- =============================================================================
